routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PasienController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false,
]);

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/pasien/detail', [PasienController::class, 'pasien_detail']);

Route::group(['middleware' => ['auth']], function () {
    Route::resource('pasien', PasienController::class);
    Route::post('/pasien/import_excel', [PasienController::class, 'import_excel']);
    Route::get('/pasien/cetak_pdf/{id}', [PasienController::class, 'cetak_pdf']);
});

app/Models/Pasien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pasien extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        // $lama = 7;
        // DB::select(DB::raw('DELETE FROM pasiens WHERE DATEDIFF(CURDATE(), tgl_pemeriksaan) > :lama'), [
        //     'lama' => $lama
        // ]);
        return view('home');
    }
}

app/Http/Controllers/PasienController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pasien;
use Illuminate\Http\Request;
use App\Imports\PasienImport;
use Barryvdh\DomPDF\Facade as PDF;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Session;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class PasienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = Pasien::query();
        if (request()->ajax()) {
            return datatables()->of($result)
                ->addColumn('action', function ($data) {
                    $action  = '<a href="/pasien/cetak_pdf/'.$data->id.'" target="_blank" class="btn-edit btn btn-primary btn-sm">PRINT</i></a>';
                    $action  .='&nbsp';
                    $action  .= '<a href="/pasien/'. $data->id.'/edit" target="_blank" class="btn-edit btn btn-info btn-sm">EDIT</i></a>';
                    return $action;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }
        return view('pasien');
    }

    public function create()
    {
        return view('create');
    }


    public function pasien_detail(Request $request)
    {
        $pasien = Pasien::where('no_sampel', $request->no_sampel)
            ->where('nik', $request->nik)
        ->first();

        return view('pasien-detail', compact('pasien'));
    }


	public function import_excel(Request $request)
	{
		// validasi
		$this->validate($request, [
			'file' => 'required|mimes:csv,xls,xlsx'
		]);

		$file = $request->file('file');
		$nama_file = rand().$file->getClientOriginalName();
		$file->move('file_pasien',$nama_file);
		Excel::import(new PasienImport, public_path('/file_pasien/'.$nama_file));
		Session::flash('sukses','Data Siswa Berhasil Diimport!');

		// alihkan halaman kembali
		return redirect('/home');
	}

    public function cetak_pdf($id)
    {
    	$pasien = Pasien::where('id', $id)->first();
        $url = env('URL_APP').'/pasien/detail?no_sampel='.$pasien->no_sampel.'&nik='.$pasien->nik;
        $qrcode = base64_encode(QrCode::format('svg')->size(150)->errorCorrection('H')->generate($url));

    	$pdf = PDF::loadview('pasien_pdf', compact('qrcode', 'pasien'));
    	return $pdf->stream('pasien.pdf');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required',
            'nik' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'alamat' => 'required',
            'tgl_penerimaan' => 'required',
            'tgl_pemeriksaan' => 'required',
            'no_sampel' => 'required',
            'status' => 'required'
        ]);

        $input = $request->all();

        $post = Pasien::create($input);

        if ($post) {
            //redirect dengan pesan sukses
            return redirect()->route('pasien.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->back()->withInput()->withErrors('Add atleast one image in the post.');
        }
    }

    public function edit($id)
    {
        $result = Pasien::find($id);
        return view('edit', compact('result'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama' => 'required',
            'nik' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'alamat' => 'required',
            'tgl_penerimaan' => 'required',
            'tgl_pemeriksaan' => 'required',
            'no_sampel' => 'required',
            'status' => 'required'
        ]);

        $input = $request->all();

        $update = Pasien::find($id)->update($input);

        if ($update) {
            //redirect dengan pesan sukses
            return redirect()->route('pasien.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->back()->withInput()->withErrors('Add atleast one image in the post.');
        }
    }
}

resources/views/create.blade.php
@extends('layouts.app')
@section('content')
<a href="{{ route('pasien.index') }}" class="btn btn-success"> PASIEN LIST</a>
<hr>
<div class="row">
    <div class="col-md-9">
        <form method="post" action="{{ route('pasien.store') }}">
            @csrf
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="nama">nama</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="nama" placeholder="Kolom Isi" value="{{ old('nama') }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="nik">nik</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="nik" placeholder="Kolom Isi" value={{ old('nik') }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tempat_lahir">tempat lahir</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="tempat_lahir" placeholder="Kolom Isi" value={{ old('tempat_lahir') }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tgl_lahir">tgl lahir</label>
                <div class="col-sm-8">
                    <input type="date" class="form-control" name="tgl_lahir" placeholder="Kolom Isi" value={{ old('tgl_lahir') }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="alamat">alamat</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="alamat" placeholder="Kolom Isi" value={{ old('alamat') }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tgl_penerimaan">tgl penerimaan</label>
                <div class="col-sm-8">
                    <input type="date" class="form-control" name="tgl_penerimaan" placeholder="Kolom Isi" value={{ old('tgl_penerimaan') }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tgl_pemeriksaan">tgl pemeriksaan</label>
                <div class="col-sm-8">
                    <input type="date" class="form-control" name="tgl_pemeriksaan" placeholder="Kolom Isi" value={{ old('tgl_pemeriksaan') }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="no_sampel">no sampel</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="no_sampel" placeholder="Kolom Isi" value={{ old('no_sampel') }}>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="status">hasil</label>
                <div class="col-sm-8">
                    <select class="form-control" name="status">
                        <option value="NEGATIF">NEGATIF</option>
                        <option value="POSITIF">POSITIF</option>
                    </select>
                </div>
            </div>
            <br>

            <div class="form-group row p-5">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="status"></label>
                <div class="col-sm-8">
                    <button type='text' class="btn btn-block btn-primary">TAMBAH PASIEN</button>
                </div>
            </div>
        </form>
    </div>

    <div>
        <div class="col-md-3">
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            <div class="alert-danger" role="alert">
                {{ $error }}
            </div>
            @endforeach
            @endif
        </div>
    </div>
</div>
@stop

resources/views/edit.blade.php
@extends('layouts.app')
@section('content')
<a href="{{ route('pasien.index') }}" class="btn btn-success">  PASIEN LIST</a>
<hr>
<div class="row">
    <div class="col-md-9">
        <form method="post" action="{{ route('pasien.update', $result->id) }}">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="nama">nama</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="nama" placeholder="Kolom Isi" value={{ $result->nama }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="nik">nik</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="nik" placeholder="Kolom Isi" value={{ $result->nik }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tempat_lahir">tempat lahir</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="tempat_lahir" placeholder="Kolom Isi" value={{ $result->tempat_lahir }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tgl_lahir">tgl lahir</label>
                <div class="col-sm-8">
                    <input type="date" class="form-control" name="tgl_lahir" placeholder="Kolom Isi" value={{ $result->tgl_lahir }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="alamat">alamat</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="alamat" placeholder="Kolom Isi" value={{ $result->alamat }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tgl_penerimaan">tgl penerimaan</label>
                <div class="col-sm-8">
                    <input type="date" class="form-control" name="tgl_penerimaan" placeholder="Kolom Isi" value={{ $result->tgl_penerimaan }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="tgl_pemeriksaan">tgl pemeriksaan</label>
                <div class="col-sm-8">
                    <input type="date" class="form-control" name="tgl_pemeriksaan" placeholder="Kolom Isi" value={{ $result->tgl_pemeriksaan }}>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="no_sampel">no sampel</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="no_sampel" placeholder="Kolom Isi" value={{ $result->no_sampel }}>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="status">hasil</label>
                <div class="col-sm-8">
                    <select class="form-control" name="status">
                        <option value="NEGATIF" {{ $result->status == 'NEGATIF' ? 'selected' : '' }}>NEGATIF</option>
                        <option value="POSITIF" {{ $result->status == 'POSITIF' ? 'selected' : '' }}>POSITIF</option>
                    </select>
                </div>
            </div>
            <br>

            <div class="form-group row p-5">
                <label class="col-sm-4 col-form-label text-uppercase text-right" for="status"></label>
                <div class="col-sm-8">
                    <button type='text' class="btn btn-block btn-primary">TAMBAH PASIEN</button>
                </div>
            </div>
        </form>
    </div>

    <div>
        <div class="col-md-3">
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            <div class="alert-danger" role="alert">
                {{ $error }}
            </div>
            @endforeach
            @endif
        </div>
    </div>
</div>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {{-- notifikasi form validasi --}}
                    @if ($errors->has('file'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('file') }}</strong>
                    </span>
                    @endif

                    {{-- notifikasi sukses --}}
                    @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                    @endif

                    <h2>HAI ADMIN, SELAMAT BERTUGAS</h2>

                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                        IMPORT DATA PCR
                    </button>
                    <a href="{{ route('pasien.index') }}" class="btn btn-success"> PRINT BARCODE</a>
                    <hr>
                    <form action="{{ route('logout') }}" method="post">
                        @csrf
                        <button class="btn btn-danger">
                            Logout
                        </button>
                    </form>

                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <form method="post" action="/pasien/import_excel" enctype="multipart/form-data">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Import Excel</h5>
                                    </div>
                                    <div class="modal-body">

                                        {{ csrf_field() }}

                                        <label>Pilih file excel</label>
                                        <div class="form-group">
                                            <input type="file" name="file" required="required">
                                        </div>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Import</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>RSUD MANOKWARI</title>

        <!-- Bootstrap CSS -->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            body {
                padding-top: 40px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>

        <!-- jQuery -->
        <script src="//code.jquery.com/jquery.js"></script>
        <!-- DataTables -->
        <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <!-- App scripts -->
        @stack('scripts')
    </body>
</html>

resources/views/pasien-detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-light">
                        <tbody>
                            <tr>
                                <td class="text-uppercase font-wight-bold">Nama</td>
                                <td>:</td>
                                <td>{{ $pasien->nama }}</td>
                            </tr>
                            <tr>
                                <td class="text-uppercase font-wight-bold">nik</td>
                                <td>:</td>
                                <td>{{ $pasien->nik }}</td>
                            </tr>
                            <tr>
                                <td class="text-uppercase font-wight-bold">tgl lahir</td>
                                <td>:</td>
                                <td>{{ $pasien->tgl_lahir }}</td>
                            </tr>
                            <tr>
                                <td class="text-uppercase font-wight-bold">tgl pemeriksaan</td>
                                <td>:</td>
                                <td>{{ $pasien->tgl_pemeriksaan }}</td>
                            </tr>
                            <tr>
                                <td class="text-uppercase font-wight-bold">no sampel</td>
                                <td>:</td>
                                <td>{{ $pasien->no_sampel }}</td>
                            </tr>
                            <tr>
                                <td class="text-uppercase font-wight-bold">status</td>
                                <td>:</td>
                                <td>{{ $pasien->status }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pasien.blade.php
@extends('layouts.app')
@section('content')
<a href="{{ route('home') }}" class="btn btn-success"> HOME</a>
<a href="{{ route('pasien.create') }}" class="btn btn-primary"> TAMBAH PASIEN</a>
<hr>
<table class="table table-bordered pt-5" id="users-table">
    <thead>
        <tr>
            <th>Nama</th>
            <th>NIK</th>
            <th>Tampat Lahir</th>
            <th>Tgl Lahir</th>
            <th>Tgl Periksa</th>
            <th>Action</th>
        </tr>
    </thead>
</table>
@stop

@push('scripts')
<script>
    $(function () {
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '/pasien',
            columns: [{
                    data: 'nama',
                    name: 'nama'
                },
                {
                    data: 'nik',
                    name: 'nik'
                },
                {
                    data: 'tempat_lahir',
                    name: 'tempat_lahir'
                },
                {
                    data: 'tgl_lahir',
                    name: 'tgl_lahir'
                },
                {
                    data: 'tgl_pemeriksaan',
                    name: 'tgl_pemeriksaan'
                },
                {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                }
            ]
        });
    });

</script>
@endpush

resources/views/pasien_pdf.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Rincian Biata Pelayanan</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <style type="text/css">
        * {
            font-size: 13px;
        }

        .page-break {
            page-break-after: always;
        }

        .text-center {
            text-align: center;
        }

        table.table-bordered {
            border: 1px solid black;
            margin-top: 20px;
        }

        table.table-bordered>thead>tr>th {
            border: 1px solid black;
        }

        table.table-bordered>tbody>tr>td {
            border: 1px solid black;
        }

        /*  */

        /* table#table-header {
            border: none;
            margin-top: 100px;
            margin-bottom: 100px;
        } */

        /* table#table-header>thead>tr>th {
            border: none;
            padding: 0px;
            margin: 0px;
        } */

        table#table-header>tbody>tr>td {
            border: none;
            padding: 2px;
            margin: 0px;
        }

        table#table-footer {
            border: none;
            margin-top: 10px;
            margin-bottom: 10px;
        }

        table#table-footer>thead>tr>th {
            border: none;
            padding: 0px;
            margin: 0px;
        }

        table#table-footer>tbody>tr>td {
            border: none;
            padding: 0px;
            margin: 0px;
        }


        /* tr td {
            padding: 2px !important;
        } */

        hr {
            display: block;
            height: 1px;
            border: 0;
            border-top: 1px solid black;
            margin: 1em 0;
            padding: 0;
        }

    </style>
    <div style="text-align:center; font-weight:bold; font-size:14px; padding:3px;">PEMERINTAH KABUPATEN MANOKWARI</div>
    <div style="text-align:center; font-weight:bold; font-size:14px; padding:3px;">BADAN LAYANAN UMUM DAERAH RUMAH SAKIT UMUM MANOKWARI</div>
    <hr>
    <div style="text-align:center; font-weight:bold; font-size:12px;">SURAT KETERANGAN PEMERIKSAAN SWAP PCR</div>
    <br>
    <div style="text-align:center; font-weight:bold; font-size:12px;">NOMOR : ................................ </div>
    <br>
    <table id="table-header" class="table" style="padding:0; margin:0;">
        <thead>
            <tr>
                <td>Nama Pasien</td>
                <td>: {{ $pasien->nama }}</td>
            </tr>

            <tr>
                <td>NIK</td>
                <td>: {{ $pasien->nik }}</td>
            </tr>

            <tr>
                <td>Tgl Lahir</td>
                <td>: {{ $pasien->tgl_lahir }}</td>
            </tr>

            <tr>
                <td>Tgl Pemeriksaan</td>
                <td>: {{ $pasien->tgl_pemeriksaan }}</td>
            </tr>

            <tr>
                <td>Tgl Penerimaan</td>
                <td>: {{ $pasien->tgl_penerimaan }}</td>
            </tr>

            <tr>
                <td>No Sample</td>
                <td>: {{ $pasien->no_sampel }}</td>
            </tr>
            <tr>
                <td>Hasil</td>
                <td>: {{ $pasien->status }}</td>
            </tr>
        </thead>
    </table>
    <br>
    <hr>
    <div style="text-align:center; font-weight:bold;font-size:12px; padding:5px;">
        <img src="data:image/png;base64, {!! $qrcode !!}">
    </div>
    <hr>
    <br>
    <br>
    <table id="table-footer" class="table text-center pt-2">
        <tr>
            <td class="text-white">Pasien Keluarga</td>
            <td>Plt. Direktur BLUD RSU Manokwari</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="text-white">................................</td>
            <td class="font-weight-bold">dr.Alwan Rimosan, Sp.B,FINACS</td>
        </tr>
        <tr>
            <td class="text-white">................................</td>
            <td>Pembina</td>
        </tr>
        <tr>
            <td class="text-white">................................</td>
            <td>NIP</td>
        </tr>
    </table>
</body>

</html>